#!/bin/bash
echo "=================================================="
echo " 🔍 COMPROBANDO ESTADO DE LOS SERVICIOS CRM"
echo "=================================================="
echo ""
echo "📦 1. Contenedores en ejecución:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo ""
echo "🌐 2. Comprobación de Endpoints HTTP:"
echo -n "  Web Login: " && curl -s -o /dev/null -w "%{http_code}\n" https://crm-salvadoraconesa.jigretera.com/login --max-time 5 || echo "ERROR"
echo -n "  Backend (/healthz): " && curl -s -o /dev/null -w "%{http_code}\n" https://crm-salvadoraconesa.jigretera.com/healthz --max-time 5 || echo "ERROR"
echo -n "  DB Check: " && curl -s https://crm-salvadoraconesa.jigretera.com/healthz/db-check --max-time 5 || echo "ERROR"
echo ""
echo "=================================================="